---
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: org1
spec:
  type: NodePort
  selector:
    app: hyperledger
    role: ca
    org: org1
    name: ca
  type: NodePort
  ports:
  - name: endpoint
    protocol: TCP
    port: 7054
    targetPort: 7054
    nodePort: 30054

---
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: org2
spec:
  type: NodePort
  selector:
    app: hyperledger
    role: ca
    org: org2
    name: ca
  type: NodePort
  ports:
  - name: endpoint
    protocol: TCP
    port: 7054
    targetPort: 7054
    nodePort: 30154
